# ----------------------------------------------------------------------------------------------------
# ESPHome configuration - This part depends on your hardware target
# ----------------------------------------------------------------------------------------------------

esphome:
  name: "esp8266"
  friendly_name: ESP8266

esp8266:
  board: esp01_1m
  restore_from_flash: true

# Enable logging
logger:
  baud_rate: 115200
  level: INFO
  logs:
    component: ERROR
    http_request.arduino: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: !secret proxy_api_encryption_key

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # If you have a WiFi activity plannification, you may have to update the reboot timeout (Default: 15min)
  reboot_timeout: 24h

# ----------------------------------------------------------------------------------------------------
# Customisation
# ----------------------------------------------------------------------------------------------------

substitutions:
  # LEDs -------------------------------------------------------------------------
  # Green LED is reflecting regulation status
  # Yellow LED is reflecting power meter
  green_led_pin: GPIO1
  green_led_inverted : "True"
  yellow_led_pin: GPIO2

  # Regulator configuration ------------------------------------------------------
  # Define GPIO pin connected to mecanical relay.
  regulator_gate_pin: GPIO0

packages:
  power_meter: !include
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/power_meter_home_assistant.yaml
    vars:
      main_power_sensor: "sensor.grid_exchange"
    refresh: 5s
  regulator: !include
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/regulator_mecanical_relay.yaml
    refresh: 5s
  solar_router: !include
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/engine_on_off.yaml
    refresh: 5s


