site_name: Solar Router for ESPHome
repo_url: https://github.com/XavierBerger/Solar-Router-for-ESPHome
repo_name: Fork me on GitHub
edit_uri: ""
copyright: © Copyright Xavier Berger - 2024-2025

nav:
  - Home: index.md
  - Disclamer: disclamer.md
  - Solar Router / Diverter: solar_router.md
  - Hardware: hardware.md
  - Firmware:
      - Overview: firmware.md
      - Installation: installation.md
      - Examples:
          - Standalone: example_standalone.md
          - With proxy: example_proxy.md
  - Power Meter:
      - Overview: power_meter.md
      - Fronius: power_meter_fronius.md
      - Home Assistant: power_meter_home_assistant.md
      - Proxy client: power_meter_proxy_client.md
      - Shelly EM: power_meter_shelly_em.md
  - Regulator:
      - Triac: regulator_triac.md
      - Solid State Relay: regulator_solid_state_relay.md
      - Mecanical relay: regulator_mecanical_relay.md
  - Engine: 
      - Progressive regulation: engine.md
      - ON/OFF regulation: engine_on_off.md
  - Energy Counter: 
      - Theorical: energy_counter_theorical.md
  - Temperature limiter:
      - Overview: temperature_limiter.md
      - Home Assistant: temperature_limiter_home_assistant.md
      - DS18B20: temperature_limiter_DS18B20.md
  - Home Assistant:
      - Recorder configuration: recorder_configuration.md
  - About:
    - ChangeLog: changelog.md
    - License: license.md
    - Contributing: contributing.md
    - compile_coverage.md
    - Alternatives: alternatives.md
    - About the project: about.md


theme:
  name: material
  features:
    - tabs
    - content.code.copy
  font:
    text: Ubuntu
    code: Ubuntu Mono

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: 🇬🇧 English
          build: true
          link: /Solar-Router-for-ESPHome/
        - locale: fr
          name: 🇫🇷 Français
          build: true
          link: /Solar-Router-for-ESPHome/fr/
          nav_translations:
            Home: Accueil
            Disclamer: Avertissement
            Solar Router / Diverter: Routeur solaire
            Hardware: Materiel
            Overview: Aperçu
            Examples: Exemples
            Standalone: Routeur autonome
            With proxy: Router utilisant un proxy
            Proxy client: Client proxy
            Mecanical relay: Relais mécanique
            Progressive regulation: Régulation progressive
            ON/OFF regulation: Regulation tout ou rien
            Theorical: Théorique
            Recorder configuration: Configuration des recorder
            Contributing: Contribution
            License: Licence
            About: A propos
            Alternatives: Alternatives
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: datetime
  - glightbox
  - include-markdown
