# ----------------------------------------------------------------------------------------------------
# ESPHome configuration - This part depends on your hardware target
# ----------------------------------------------------------------------------------------------------

esphome:
  name: wt32-eth01-2
  friendly_name: wt32-eth01-2

esp32:
  board: wt32-eth01
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 115200
  level: INFO
  logs:
    component: ERROR
    light: ERROR
    http_request.arduino: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: !secret wt32_eth01_2_api_encryption_key

# Enable over-the-air updates
ota:
  - platform: esphome
    password: !secret wt32_eth01_2_ota_password

# WiFi connection
# To activate WiFi :
#   Uncomment this section parameters and comment RJ45 ethernet section
#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
#  # If you have a WiFi activity plannification, you may have to update the reboot timeout (Default: 15min)
#  reboot_timeout: 24h

# Configure RJ45 ethernet
# To activate RJ45 ethernet :
#   Uncomment this section parameters and comment WiFi section 
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

# Activate web interface
web_server:
  port: 80

# ----------------------------------------------------------------------------------------------------
# Customisation
# ----------------------------------------------------------------------------------------------------
packages:
  common: !include
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/common.yaml
    refresh: 5s
  power_meter: !include
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/power_meter_fronius.yaml
    vars:
      power_meter_ip_address: "192.168.1.21"
    refresh: 5s
  regulator: !include
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/regulator_solid_state_relay.yaml
    vars:
      regulator_gate_pin: GPIO14
    refresh: 5s
  solar_router: !include
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/engine_on_off.yaml
    vars:
      green_led_pin: GPIO32
      yellow_led_pin: GPIO33
    refresh: 5s
