# ----------------------------------------------------------------------------------------------------
# ESPHome configuration - This part depends on your hardware target
# ----------------------------------------------------------------------------------------------------

esphome:
  name: "solar-water-heater"
  friendly_name: "solar-water-heater"
  min_version: 2025.3.2

esp32:
  board: wt32-eth01
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 115200
  level: INFO
  logs:
    component: ERROR
    light: ERROR
    http_request.arduino: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: !secret solar_water_heater_api_encryption_key

# Enable over-the-air updates
ota:
  - platform: esphome
    password: !secret solar_water_heater_ota_password

# WiFi connection
# To activate WiFi :
#   Uncomment this section parameters and comment RJ45 ethernet section
#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
#  # If you have a WiFi activity plannification, you may have to update the reboot timeout (Default: 15min)
#  reboot_timeout: 24h

# Configure RJ45 ethernet
# To activate RJ45 ethernet :
#   Uncomment this section parameters and comment WiFi section 
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

# Activate web interface
web_server:
  port: 80

# ----------------------------------------------------------------------------------------------------
# Customisation
# ----------------------------------------------------------------------------------------------------
packages:
  solar_router:
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    ref: chore/code_update
    refresh: 1d
    files:
      - path: solar_router/common.yaml
      - path: solar_router/power_meter_fronius.yaml
        vars:
          power_meter_ip_address: "192.168.1.21"
      - path: solar_router/regulator_triac.yaml
        vars:
          regulator_gate_pin: GPIO17 # TXD
          regulator_zero_crossing_pin: GPIO39
      - path: solar_router/engine_1dimmer.yaml
        vars:
          green_led_pin: GPIO32 # CFG
          yellow_led_pin: GPIO14
      - path: solar_router/energy_counter_theorical.yaml
      - path: solar_router/temperature_limiter_DS18B20.yaml
        vars:
          DS18B20_pin: GPIO02
          temperature_update_interval: 1s
          red_led_pin: GPIO5
      - path: solar_router/temperature_fan_control.yaml
        vars:
          fan_control_pin: GPIO4
