# ----------------------------------------------------------------------------------------------------
# Calculate daily energy diverted
# ----------------------------------------------------------------------------------------------------

# Define the power of load plugged on the solar router
number:
  - platform: template
    name: "Load power"
    id: load_power
    min_value: 0
    max_value: 99999
    step: 1
    unit_of_measurement: "W"
    optimistic: True
    restore_value: true
    
# Script updating the power consumed counter
script:
  - id: energy_diverted_counter
    mode: single
    then:
      - lambda: |-
          double diverted_energy = id(load_power).state*id(router_level).state / 100;
          if (id(consumption).state >= diverted_energy or isnan(id(consumption).state)) 
          {
              // Power diverted is consumed (or we don't know the consumption)
              id(power_divertion).publish_state(diverted_energy);
          }
          else
          {
              // Power diverted is not consumed
              id(power_divertion).publish_state(0.0);
          }


# Sensor showing the actual energy diverted consumption
sensor:
  - id: energy_diverted
    platform: integration
    name: 'Total energy diverted'
    sensor: power_divertion
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    time_unit: h
    restore: true
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

  - platform: template
    name: Power divertion
    id: power_divertion
    unit_of_measurement: 'W'
    device_class: power

# Enable time component to 
#  - Update energy diverted counter
#  - Reset energy counter at midnight
time:
  - platform: sntp
    on_time:
      # Trigger action every second
      - seconds: /1
        then:
          - script.execute: energy_diverted_counter
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - sensor.integration.reset: energy_diverted