# ----------------------------------------------------------------------------------------------------
# User interaction
# ----------------------------------------------------------------------------------------------------
packages:
  - !include engine_common.yaml

sensor:
  - platform: template
    name: "Relay 1 Countdown"
    id: relay1_tempo_counter
    device_class: "duration"
    state_class: "measurement"
    filters:
      - clamp:
          min_value: 0
  - platform: template
    name: "Relay 2 Countdown"
    id: relay2_tempo_counter
    device_class: "duration"
    state_class: "measurement"
    filters:
      - clamp:
          min_value: 0
  - platform: template
    name: "Relay 3 Countdown"
    id: relay3_tempo_counter
    device_class: "duration"
    state_class: "measurement"
    filters:
      - clamp:
          min_value: 0
  - platform: template
    name: "Regulator Opening"
    id: regulator_opening
    unit_of_measurement: "%"
    update_interval: 1s
    internal: ${hide_regulators}
    on_value:
      then:
        - script.execute: regulation_control

switch:
  # Define is router is active or not
  # When switch is ON, pooling timer will trigger every seconds
  - platform: template
    name: "Activate Solar Routing"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    id: activate
    on_turn_on:
      then:
        - light.turn_on: green_led
        - lambda: |-
            id(relay1_tempo_counter).publish_state(id(full_power_duration).state);
            id(relay2_tempo_counter).publish_state(id(full_power_duration).state);
            id(relay3_tempo_counter).publish_state(id(full_power_duration).state);
            id(power_meter_activated) = 1;
    on_turn_off:
      then:
        - light.turn_off: green_led
        - lambda: |- 
            id(router_level).publish_state(0);
            id(real_power).publish_state(NAN);
            id(consumption).publish_state(NAN);
            id(relay1_tempo_counter).publish_state(0);
            id(relay2_tempo_counter).publish_state(0);
            id(relay3_tempo_counter).publish_state(0);
            id(power_meter_activated) = 0;
            id(energy_divertion1).turn_off();
            id(energy_divertion2).turn_off();
            id(energy_divertion3).turn_off();
            id(regulator_opening).publish_state(0);

  - platform: template
    name: "Energy divertion Relay 1"
    id: energy_divertion1
    optimistic: True
    internal: ${hide_regulators}
    disabled_by_default: True
    on_turn_on:
      then:
        - script.execute: relay1_regulation_control
        - lambda: id(regulator_opening).publish_state(0);
    on_turn_off:
      then:
        - script.execute: relay1_regulation_control
  - platform: template
    name: "Energy divertion Relay 2"
    id: energy_divertion2
    optimistic: True
    internal: ${hide_regulators}
    disabled_by_default: True
    on_turn_on:
      then:
        - script.execute: relay2_regulation_control
        - lambda: id(regulator_opening).publish_state(0);
    on_turn_off:
      then:
        - script.execute: relay2_regulation_control
  # Relay3 - Define the bypass relay
  # When bypass relay is ON, the regulator opening is set to 0
  # When bypass relay is OFF, the regulator opening is set to the value defined by the solar router
  - platform: template
    name: "Energy divertion Realy 3 Bypass"
    id: energy_divertion3
    optimistic: True
    internal: ${hide_regulators}
    disabled_by_default: True
    on_turn_on:
      then:
        - script.execute: relay3_regulation_control
        - lambda: id(regulator_opening).publish_state(0);
    on_turn_off:
      then:
        - script.execute: relay3_regulation_control


number:
  # Router level from 0 to 100
  # This value serves two purposes:
  # 1. When solar routing is disabled: Acts as a manual control to set the router level
  # 2. When solar routing is enabled: Automatically updated to reflect the current router level
  #    Note: Manual adjustments via slider while routing is enabled are not recommended as they will be
  #          immediately overridden by the solar router's automatic control
  - platform: template
    name: "Router Level"
    id: router_level
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: "%"
    optimistic: True
    mode: slider
    on_value:
      then:
        - lambda: |-
            double current_router_level = id(router_level).state;
            if (current_router_level >= 100.0) {
              id(energy_divertion1).turn_on();
              id(energy_divertion2).turn_on();
              if (id(relay3_tempo_counter).state <= 0) {
                id(energy_divertion3).turn_on();
              } else {
                id(energy_divertion3).turn_off();
                id(regulator_opening).publish_state(100.0);
              }
            } else if (current_router_level >= 66.66666666) {
              id(energy_divertion1).turn_on();
              id(energy_divertion3).turn_off();
              if (id(relay2_tempo_counter).state <= 0) {
                id(energy_divertion2).turn_on();
                id(regulator_opening).publish_state(3.0 * current_router_level - 200);
              } else {
                id(energy_divertion2).turn_off();
                id(regulator_opening).publish_state(100.0);
              }
            } else if (current_router_level >= 33.33333333) {
              id(energy_divertion2).turn_off();
              id(energy_divertion3).turn_off();
              if (id(relay1_tempo_counter).state <= 0) {
                id(energy_divertion1).turn_on();
                id(regulator_opening).publish_state(3.0 * current_router_level - 100);
              } else {
                id(energy_divertion1).turn_off();
                id(regulator_opening).publish_state(100.0);
              }
            } else {
              id(energy_divertion1).turn_off();
              id(energy_divertion2).turn_off();
              id(energy_divertion3).turn_off();
              id(regulator_opening).publish_state(3.0 * current_router_level);
            }
        - if:
            condition:
              number.in_range:
                id: router_level
                above: 1
            then:
              - light.turn_on:
                  id: green_led
                  effect: blink
            else:
              - light.turn_off: green_led
              - if:
                  condition:
                    - switch.is_on: activate
                  then:
                    - light.turn_on: green_led

  # Define the number of consecutive regulations where regulator is at 33.3333% or 66.6666% or 100% (full power of dimmer) before activating bypass relay
  # When regulator is at 33.3333% or 66.6666% or 100% and delta is still positive, this counter is incremented
  # When counter reach full_power_duration, bypass relay is activated
  # Counter is reset to 0 when regulator is not at 33.3333% or 66.6666% or 100% or when delta is negative
  - platform: template
    name: "Bypass tempo"
    id: full_power_duration
    optimistic: True
    min_value: 0
    max_value: 300
    step: 1
    initial_value: 30
    restore_value: True
    on_value:
      then:
        - if:
            condition:
              - switch.is_on: activate
            then:
              - lambda: |-
                  id(relay1_tempo_counter).publish_state(id(full_power_duration).state);
                  id(relay2_tempo_counter).publish_state(id(full_power_duration).state);
                  id(relay3_tempo_counter).publish_state(id(full_power_duration).state);

  # Define the reactivity of router level
  - platform: template
    name: "Up Reactivity" 
    id: up_reactivity
    optimistic: True
    restore_value: True
    mode: box
    min_value: 1
    max_value: 100
    initial_value: 10
    unit_of_measurement: ""
    step: 1
  - platform: template
    name: "Down Reactivity"
    id: down_reactivity
    optimistic: True
    restore_value: True
    mode: box
    min_value: 1
    max_value: 100
    initial_value: 10
    unit_of_measurement: ""
    step: 1

  # Define the target level of grid exchange
  #   0 : no exchange
  #  <0 : continue the send energy to the grid
  #  >0 : pull energy from the grid to better confort
  - platform: template
    name: "Target grid exchange"
    id: target_grid_exchange
    optimistic: True
    restore_value: True
    mode: box
    min_value: -99999
    max_value: 99999
    initial_value: 0
    unit_of_measurement: "W"
    step: 1

# ----------------------------------------------------------------------------------------------------
# Define scripts for power collection or energy regulation
# ----------------------------------------------------------------------------------------------------

script:
  # Manage energy regulation
  # Calculate the delta of percentage to apply to the router level status to go closer to the
  # objective. Closer we are to the objective smaller are the steps. Reactivity parameter is
  # doing a ponderation on this parameter to avoid resonance effects.
  - id: energy_regulation
    mode: single
    then:
      # Define the reouter level based on power measured and grid exchange target
      # The value of regulator is a precentage and is then limited to the range 0 100
      - lambda: |-
          // Safety check: Disable regulation if power readings are invalid or safety is triggered
          if (isnan(id(real_power).state) or id(safety_limit)){
            id(router_level).publish_state(0);
            id(relay1_tempo_counter).publish_state(id(full_power_duration).state);
            id(relay2_tempo_counter).publish_state(id(full_power_duration).state);
            id(relay3_tempo_counter).publish_state(id(full_power_duration).state);
            return;
          }

          // Calculate the power difference and adjust the regulator opening percentage
          double real_power_state = id(real_power).state;
          double target_grid_exchange_state = id(target_grid_exchange).state;
          double reactivity_state = NAN;
          if (real_power_state >= target_grid_exchange_state) {
              reactivity_state = id(down_reactivity).state;
          } else {
              reactivity_state = id(up_reactivity).state;
          }
    
          double delta = -1*(real_power_state-target_grid_exchange_state)*reactivity_state/3000;
          // Determine the new regulator status
          double new_router_level = id(router_level).state + delta;
          new_router_level = std::max(0.0, std::min(100.0, new_router_level));

          if (new_router_level >= 100.0) {
            id(relay3_tempo_counter).publish_state(id(relay3_tempo_counter).state - 1);
            id(relay2_tempo_counter).publish_state(0);
            id(relay1_tempo_counter).publish_state(0);
          } else if (new_router_level >= 66.66666666) {
            if (id(relay2_tempo_counter).state > 0) {
              new_router_level = 66.66666666;
            }

            id(relay3_tempo_counter).publish_state(id(full_power_duration).state);
            id(relay2_tempo_counter).publish_state(id(relay2_tempo_counter).state - 1);
            id(relay1_tempo_counter).publish_state(0);
          } else if (new_router_level >= 33.33333333) {
            if (id(relay1_tempo_counter).state > 0) {
              new_router_level = 33.33333333;
            }

            id(relay3_tempo_counter).publish_state(id(full_power_duration).state);
            id(relay2_tempo_counter).publish_state(id(full_power_duration).state);
            id(relay1_tempo_counter).publish_state(id(relay1_tempo_counter).state - 1);
          } else {
            id(relay3_tempo_counter).publish_state(id(full_power_duration).state);
            id(relay2_tempo_counter).publish_state(id(full_power_duration).state);
            id(relay1_tempo_counter).publish_state(id(full_power_duration).state);
          }

          id(router_level).publish_state(new_router_level);