<<: !include power_meter_common.yaml

esphome:
  min_version: 2024.11.1

# ----------------------------------------------------------------------------------------------------
# Use http request component
# ----------------------------------------------------------------------------------------------------

http_request:
  id: http_request_data
  useragent: esphome/device
  timeout: 10s
  verify_ssl: False

# ----------------------------------------------------------------------------------------------------
# Define scripts for power collection
# ----------------------------------------------------------------------------------------------------

script:
  # Get power reports from another PowerMEter and update globals (real_power)
  # Information are provided as json. Power exchanged with the grid is names "Value"
  - id: power_meter_source
    mode: single
    then:
      - if:
          condition:
            lambda: 'return network::is_connected();'
          then:
            - http_request.get:
                url: http://${power_meter_ip_address}/sensor/real_power
                capture_response: true
                max_response_buffer_size: 4096
                on_response:
                  then:
                    - lambda: |-
                        if (response->status_code != 200) {
                            ESP_LOGW("custom", "HTTP Request failed with status: %d", response->status_code);
                            id(real_power).publish_state(NAN);
                        } else {
                          bool parse_success = json::parse_json(body, [](JsonObject root) -> bool {
                              if (!root["value"].is<JsonObject>()) {
                                  ESP_LOGW("custom", "Invalid JSON structure");
                                  return false;
                              }
                              id(real_power).publish_state(root["value"].as< float >());
                              return true;
                          });

                          if (!parse_success) {
                              ESP_LOGW("custom", "JSON Parsing failed");
                              id(real_power).publish_state(NAN);
                          }
                        }
                on_error:
                  then:
                    - lambda: |-
                        ESP_LOGW("custom", "HTTP Request failed or timeout occurred");
                        id(real_power).publish_state(NAN);
            - http_request.get:
                url: http://${power_meter_ip_address}/sensor/consumption
                capture_response: true
                max_response_buffer_size: 4096
                on_response:
                  then:
                    - lambda: |-
                        if (response->status_code != 200) {
                            ESP_LOGW("custom", "HTTP Request failed with status: %d", response->status_code);
                            id(consumption).publish_state(NAN);
                        } else {
                          bool parse_success = json::parse_json(body, [](JsonObject root) -> bool {
                              if (!root["value"].is<JsonObject>()) {
                                  ESP_LOGW("custom", "Invalid JSON structure");
                                  return false;
                              }
                              id(consumption).publish_state(root["value"].as< float >());
                              return true;
                          });

                          if (!parse_success) {
                              ESP_LOGW("custom", "JSON Parsing failed");
                              id(consumption).publish_state(NAN);
                          }
                        }
                on_error:
                  then:
                    - lambda: |-
                        ESP_LOGW("custom", "HTTP Request failed or timeout occurred");
                        id(consumption).publish_state(NAN);
time:
  - platform: sntp
    on_time:
      - seconds: /1
        then:
          - if:
              condition:
                - lambda: return id(power_meter_activated) != 0;
              then:
                - script.execute: power_meter_source
