# ----------------------------------------------------------------------------------------------------
# Define scripts for energy divertion
# ----------------------------------------------------------------------------------------------------
substitutions:
  regulator_zero_cross_inverted: yes
  
script:
  # Apply regulation on triac using light component
  - id: regulation_control
    mode: single
    then:
      # Apply opening level on triac using light component
      - light.turn_on:
          id: dimmer_controller
          brightness: !lambda return id(regulator_opening).state/100.0;
          state: true          

# ----------------------------------------------------------------------------------------------------
# Triac control
# ----------------------------------------------------------------------------------------------------

# Control the triac through GPIO
output:
  - platform: ac_dimmer
    id: ac_dimmer_output
    gate_pin: ${regulator_gate_pin}
    zero_cross_pin:
      number: ${regulator_zero_crossing_pin}
      mode:
        input: true
      inverted: ${regulator_zero_cross_inverted}

# Manage triac opening with light component brightness
light:
  - platform: monochromatic
    id: dimmer_controller
    output: ac_dimmer_output
    internal: True
    default_transition_length: 0s
